### ISSUE TITLE
role-lsyncd doesn't exist yet

### ISSUE THREAD

**Issue by bstinsonmhk** [CentOS/ansible-infra-playbooks#3]
Running a couple of --check --diff runs from a new fake control host.

https://github.com/CentOS/ansible-infra-playbooks/blob/e95437fcb708a691be7af54d8c64003401f958bc/role-all.yml#L14

We should push the role-lsyncd playbook so that the all playbook works properly

**Comment by arrfab** [comment]
role template/boilerplate was pushed, but only the missing role file wasn't generated/pushed

**Comment by arrfab** [comment]
Fixed by last commit/push
